model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "weights/llama-2-7b-chat-hf"
  ckpt: "weights/minigpt_med_pretrained.pth"
  lora_r: 64
  lora_alpha: 16

datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  rsna:
    eval_file_path: data/annotations/RSNA_test.json
    img_path: data/rsna/RSNA-bbox-1024
    max_new_tokens: 100
    batch_size: 10

  radvqa:
    eval_file_path: data/annotations/vqa_test.json
    img_path: data/radvqa/imgs
    max_new_tokens: 300
    batch_size: 10

  indiana_cxr:
    eval_file_path: data/annotations/indiana_test.json
    img_path: data/Chest X/images
    max_new_tokens: 300
    batch_size: 10

  nlst:
    eval_file_path: data/annotations/NLST_test.json
    img_path: data/nlst/NLST_images
    max_new_tokens: 100
    batch_size: 10

  SLAKE:
    eval_file_path: data/annotations/grounding_test_SLAKE.json
    img_path: data/slake/imgs
    max_new_tokens: 100
    batch_size: 10

  slake_vqa:
    eval_file_path: data/annotations/VQA_test_SLAKE.json
    img_path: data/slake/imgs
    max_new_tokens: 300
    batch_size: 10


run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: experiments/eval
