datasets:
  slake_vqa:
    data_type: images
    build_info:
      image_path: data/slake/imgs
      ann_path: data/annotations/VQA_train_SLAKE.json
      val_ann_path: data/annotations/VQA_val_SLAKE.json
